package Locators;

import org.openqa.selenium.By;

public class DashboardLocators {
	
	//Locators for HR dashboard_tab
	public By dashboardButton = By.xpath("//div[@class='appmagic-content-control-name appmagic-control-view canvasContentDiv _vst_']//div[text()='Timesheet Dashboard']");
//    public By dashboardButton = By.cssSelector("#publishedCanvas > div > div.app-canvas > div:nth-child(4) > div > div > div:nth-child(9) > div > div > div > div > div:nth-child(2) > div > div > div > div > div.virtualized-gallery.hideScrollbar > div > div > div:nth-child(1) > div.canvasContentDiv.container_1vt1y2p > div > div:nth-child(2) > div > div > div > div > button");
    public By greenrl = By.xpath("//div[text()='Amisha Sen']");
    public By purplepl = By.cssSelector("#publishedCanvas > div > div.app-canvas > div:nth-child(4) > div > div > div:nth-child(8) > div > div > div > div > div > div > div > div > div > div > div > div:nth-child(43) > div > div > div > div > div.virtualized-gallery.hideScrollbar > div > div > div:nth-child(9) > div.canvasContentDiv.container_1vt1y2p > div > div:nth-child(1) > div > div > div > div > div");
    public By blackuser = By.xpath("//div[text()='A test']");
	
	
	//Locators for PL dashboard_tab
    public By Leaddb = By.xpath("//div[text()='Lead Dashboard']");
    public By clickreporteePL = By.xpath("(//div[contains(text(), 'A test')]//ancestor::div[@class='container_1f0sgyp']//child::div)[1]");
    public By switchoffpl = By.cssSelector("div[role='switch'] > .appmagic-toggleSwitch-off");
	public By switchonpl = By.cssSelector("div[role='switch'] > .appmagic-toggleSwitch-on");
	public By allclientsPL = By.xpath("//div[text()='Associated Clients']");
	public By claimedtaskPL = By.xpath("//div[text()='Claimed Task']");
	public By yeardropdown_pl = By.xpath("//div[contains(@id, 'publishedCanvas')]//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'scrollContainer')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card')]//div[53]//div[contains(@class, 'react-knockout-control')]//div//div//div[contains(@role, 'button')]");
	
	public By chooseyearpl = By.xpath("//div[contains(@class, 'appmagic-dropdownFlyout')]//div[contains(@role, 'listbox')]/div[2]");
	public By rightarrowPL = By.xpath("//div[contains(@id, 'publishedCanvas')]//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'appmagic-fluidGrid')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-card')]//div[58]//div[contains(@role, 'list')]//div[contains(@class, 'react-gallery-items-window')]/div[1]//div[contains(@class, 'canvasContentDiv')]//div/div[6]//div[contains(@class, 'react-knockout-control')]/div");
    public By approbebtn = By.xpath("//div[text()='Approve']");
    public By reporteedropdown = By.xpath("//div[contains(@id, 'publishedCanvas')]//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'scrollContainer')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card')]//div[50]//div[contains(@class, 'react-knockout-control')]//div//div//div[contains(@role, 'button')]");
    public By choosereportee = By.xpath("//div[contains(@class, 'appmagic-dropdownFlyout')]//div[contains(@role, 'listbox')]/div[2]");
	public By filterbtnPL = By.cssSelector("[data-control-id='2044'] [touch-action]");

	
	public By notstartedyetPL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=15]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By draftPL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=16]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By SubmittedPL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=17]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Partially_SubmittedPL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=18]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By ApprovedPL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=19]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Partially_ApprovedPL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=20]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By RejectedPL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=21]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");

	public By choosereporteenew = By.xpath("//div[contains(@class, 'appmagic-dropdownFlyout')]//div[contains(@role, 'listbox')]/div[6]");
	public By submittedtimesheetPL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'appmagic-fluidGrid')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=63]//div[@role='list']//div[@role='listitem']//div[contains(@class, 'canvasContentDiv') and contains(@class, 'container')]//div[position()=2]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	
	public By consumedhrsPL = By.xpath("div:nth-of-type(2) > .canvasContentDiv.container_1vt1y2p  .appmagic-content-control-name.appmagic-control-view.canvasContentDiv div[role='list']  .react-gallery-items-window > div:nth-of-type(1) > .canvasContentDiv.container_1vt1y2p > div > div:nth-of-type(4) div[role='presentation'] > .appmagic-label-text");
    
  
	//Locators for Editor dashboard_tab
	public By admindb = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[position()=4]//div//div//div[position()=9]//div[contains(@class, 'appmagic-borderfill-container')]//div//div//div//div[position()=2]//div[@role='list']//div[contains(@class, 'react-gallery-items-window')]//div[position()=1]//div[contains(@class, 'canvasContentDiv') and contains(@class, 'container')]//div[position()=2]//button");
	public By edreportee = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[position()=4]//div//div//div[position()=8]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'appmagic-fluidGrid')]//div//div[contains(@class, 'scrollContent_1xligvk')]//div[contains(@class, 'scrollContent_1xligvk')]//div//div[contains(@class, 'appmagic-card') and contains(@class, 'card_c5uw0h')]//div[position()=43]//div[@role='list']//div[contains(@class, 'react-gallery-items-window')]//div[position()=2]//div[contains(@class, 'canvasContentDiv') and contains(@class, 'container')]//div[position()=1]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By switchoff = By.xpath("div[role='switch'] > .appmagic-toggleSwitch-off\r\n");
	public By switchon = By.xpath("div[role='switch'] > .appmagic-toggleSwitch-on");
	public By allclients_editor = By.xpath("//div[text()='All Clients']");
	public By claimedtask_editor = By.xpath("//div[text()='Claimed Task']");
	
	
	public By yeardropdown = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[position()=4]//div//div//div[position()=8]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'scrollContainer')]//div[contains(@class, 'scrollContent_1xligvk')]//div[contains(@class, 'scrollContent_1xligvk')]//div//div[contains(@class, 'appmagic-card') and contains(@class, 'card_c5uw0h')]//div[position()=51]");
	public By selectyear = By.xpath("//div[contains(@class, 'appmagic-dropdownFlyout')]//div[@role='listbox']//div[position()=3]");
	
	public By rightarrow = By.cssSelector("#publishedCanvas > div > div.app-canvas > div:nth-child(4) > div > div > div:nth-child(8) > div > div > div > div > div > div > div > div > div > div > div > div:nth-child(63) > div > div > div > div > div.virtualized-gallery.hideScrollbar > div > div > div:nth-child(1) > div.canvasContentDiv.container_1vt1y2p > div > div:nth-child(4) > div > div > div > div");
	public By approvebtn = By.cssSelector("#publishedCanvas > div > div.app-canvas > div:nth-child(5) > div > div > div:nth-child(32) > div > div > div > div > button");
	public By repddeditor = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=56]//div[contains(@class, 'react-knockout-control')]//div");
	public By repnameeditor = By.xpath("//div[contains(@class, 'drop-content')]//div[contains(@class, 'appmagic-dropdownFlyout')]//div[@role='listbox']//div[position()=8]");
	public By filterbtneditor = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=55]//div[contains(@class, 'react-knockout-control')]//div");

	public By notstartedyeteditor = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=15]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By drafteditor = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=16]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Submittededitor = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=17]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Partially_Submittededitor = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=18]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Approvededitor = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=19]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Partially_Approvededitor = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=20]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Rejectededitor = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=21]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	
	public By submittedtimesheeteditor = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'appmagic-fluidGrid')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=63]//div[@role='list']//div[@role='listitem']//div[contains(@class, 'canvasContentDiv') and contains(@class, 'container')]//div[position()=2]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");

	
	public By notify = By.cssSelector("#publishedCanvas > div > div.app-canvas > div:nth-child(4) > div > div > div:nth-child(7) > div > div > div > div");
	public By refresh = By.cssSelector("#publishedCanvas > div > div.app-canvas > div:nth-child(4) > div > div > div:nth-child(6) > div > div > div > div");
	public By approvenotify = By.cssSelector("[data-lp-id='Button - 216\\|Button - 216\\|undefined'] [class='ms-Button-label label-160']");
	public By selectdate = By.cssSelector("input[role='combobox']");
	
	public By rejectbtn = By.cssSelector(".ms-Button.ms-Button--primary.root-170 .label-160.ms-Button-label");
	public By rejectreason = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[position()=4]//div//div[position()=16]//div[@role='presentation']//div[@role='presentation']//textarea");
	
	public By close = By.cssSelector("div[role='presentation'] > .ms-Button.ms-Button--primary.root-164");
	public By repyy = By.cssSelector("#publishedCanvas > div > div.app-canvas > div:nth-child(4) > div > div > div:nth-child(8) > div > div > div > div > div > div > div > div > div > div > div > div:nth-child(51)");
			
	
	//Locators for RL dashboard_tab
	public By teamsdb = By.xpath("//div[text()='Team Dashboard']");
	public By clickreporteeRL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[position()=4]//div//div[position()=6]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'appmagic-fluidGrid')]//div//div[contains(@class, 'scrollContent_1xligvk')]//div//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card_c5uw0h')]//div[position()=39]//div[@role='list']//div[@role='listitem']//div[contains(@class, 'canvasContentDiv') and contains(@class, 'container_1vt1y2p')]//div//div[position()=1]//div[@role='presentation']");
	public By associatedclients = By.xpath("//div[text()='Associated Clients']");
	public By claimedtask_RL = By.xpath("//div[text()='Claimed Task under My Leadership for Financial Year :']");
	public By financialdropdown = By.xpath("//div[@data-control-name='TeamDashFinancialYrDrpdwn']");
	public By selectyear_RL = By.xpath("//div[contains(@class, 'drop-content')]//div[contains(@class, 'appmagic-dropdownFlyout')]//div[@role='listbox']/div[1]");
	public By rightarrow_RL = By.cssSelector("div:nth-of-type(1) > .canvasContentDiv.container_1vt1y2p > div > div:nth-of-type(6) .powerapps-icon");
	public By approvebtn_Rl = By.xpath("//div[text()='Approve']");
	public By reporteedropdown_RL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'scrollContainer')]/div[contains(@class, 'scrollContent')]/div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card')]/div[51]//div[contains(@class, 'react-knockout-control')]/div/div");
	public By filterbtn_RL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[4]//div//div[5]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'scrollContent')]//div//div[contains(@class, 'appmagic-card')]//div[52]//div[contains(@class, 'react-knockout-control')]/div");
	
	public By notstartedyetRL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=15]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By draftRL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=16]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By SubmittedRL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=17]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Partially_SubmittedRL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=18]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By ApprovedRL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=19]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Partially_ApprovedRL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=20]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By RejectedRL = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=21]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");

	public By consumedhrsRL = By.xpath("div:nth-of-type(2) > .canvasContentDiv.container_1vt1y2p  .appmagic-content-control-name.appmagic-control-view.canvasContentDiv div[role='list']  .react-gallery-items-window > div:nth-of-type(1) > .canvasContentDiv.container_1vt1y2p > div > div:nth-of-type(4) div[role='presentation'] > .appmagic-label-text");

	public By calculatebtn = By.cssSelector("div[role='presentation'] > .ms-Button.ms-Button--primary.root-158");
	
	
	
	//Locators for Viewer dashboard_tab
	public By adminViewer = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'react-gallery-items-window')]//ancestor::div[contains(@class, 'canvasContentDiv')]//div[position()=2]//button//div");
	public By clickreporteeViewer = By.xpath("(//div[contains(text(), 'A test')]//ancestor::div[@class='container_1f0sgyp']//child::div)[1]");
	public By blackuserViewer = By.xpath("(//div[contains(text(), 'A test')]//ancestor::div[@class='container_1f0sgyp']//child::div)[1]");
	public By switchoffViewer = By.cssSelector("div[role='switch'] > .appmagic-toggleSwitch-off");
	public By switchonViewer = By.cssSelector("div[role='switch'] > .appmagic-toggleSwitch-on");
	public By allclients = By.xpath("//div[text()='All Clients']");
	public By claimedtask = By.xpath("//div[text()='Claimed Task']");
	public By yeardropdown_Viewer = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[51]");
	public By chooseyear = By.xpath("//div[contains(@class, 'appmagic-dropdownFlyout')]//div[@role='listbox']//div[position()=3]");
	
	
	public By repddViewer = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=56]//div[contains(@class, 'react-knockout-control')]//div");
	public By repnameViewer = By.xpath("//div[contains(@class, 'drop-content')]//div[contains(@class, 'appmagic-dropdownFlyout')]//div[@role='listbox']//div[position()=8]");
	public By filterbtn = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=55]//div[contains(@class, 'react-knockout-control')]//div");
	
	public By notstartedyetViewer = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=15]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By draft = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=16]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Submitted = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=17]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Partially_Submitted = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=18]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Approved = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=19]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Partially_Approved = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=20]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");
	public By Rejected = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'scrollContainer') and contains(@class, 'scrollbar')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=21]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");

	public By submittedtimesheet = By.xpath("//div[@id='publishedCanvas']//div[contains(@class, 'app-canvas')]//div[contains(@class, 'appmagic-borderfill-container')]//div[contains(@class, 'appmagic-border-inner')]//div[contains(@class, 'appmagic-fluidGrid')]//div[contains(@class, 'scrollContent')]//div[contains(@class, 'appmagic-card') and contains(@class, 'card')]//div[position()=63]//div[@role='list']//div[@role='listitem']//div[contains(@class, 'canvasContentDiv') and contains(@class, 'container')]//div[position()=2]//div[@role='presentation']//div[contains(@class, 'appmagic-label-text')]");




}

